# Generated by Django 3.0.5 on 2020-05-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atttp', '0004_auto_20200504_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='igra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamehead', to='atttp.GameHead'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='niz',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
