# Generated by Django 3.0.5 on 2020-05-22 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atttp', '0006_auto_20200520_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='rezultat_1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='rezultat_2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
